#!/usr/bin/env bash

# Tag the commit corresponding to the current version and push to GitHub, triggering a release via CI.
#
# This script must be run from the root of the repository.

set -eux -o pipefail

bumpversion="python -m bumpversion"

if $bumpversion > /dev/null != 2; then
  echo "bump2version must be installed to bump versions; install using 'pip install bump2version'"
  exit 1
fi

# cd plugin
CURRENT_VERSION=$($bumpversion --dry-run --list minor | grep "^current_version" | sed -r s,"^.*=",,)
# Get the line number of the version field in package.json.
version_line_number=$(grep -n '"version": "'"$CURRENT_VERSION"'"' plugin/package.json | sed 's/:.*//')
# Get the SHA of the most recent bumpversion commit by running git blame on the version line of package.json.
commit=$(git blame -L "$version_line_number","$version_line_number" plugin/package.json | cut -d' ' -f1)
# Get the commit message, for use in the annotated tag.
tag_name="v$CURRENT_VERSION"
message=$(git log -n 1 --pretty=format:%s "$commit")
git tag -am "$message" "$tag_name" "$commit"
git push --tags origin "$tag_name"
