name: Bump Version and Prepare Release

run-name: Bump Version triggered by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: Type of the update [build|release|patch|minor|major]
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Hello World
        run: python -m venv .venv && source .venv/bin/activate
        shell: sh

      - name: Install bump version
        run: pip install bump2version
        shell: sh

      - name: Install bump version
        run: pip install bump2version
        shell: sh

      - name: Bump Version
        run: ./scripts/bump-plugin ${{ inputs.updateType }}
